Thu Dec 29 22:03:02 2022 - INFO  - Start environmental preparation.
Thu Dec 29 22:07:35 2022 - INFO  - End of environmental preparation!
Thu Dec 29 22:07:37 2022 - INFO  - Start to run testcase.
cobblerd does not appear to be running/accessible: ConnectionRefusedError(111, 'Connection refused')
Traceback (most recent call last):
  File "/usr/bin/cobbler", line 35, in <module>
    sys.exit(app.main())
  File "/usr/lib/python3.9/site-packages/cobbler/cli.py", line 852, in main
    rc = cli.run(sys.argv)
  File "/usr/lib/python3.9/site-packages/cobbler/cli.py", line 418, in run
    self.token = self.remote.login("", self.shared_secret)
  File "/usr/lib64/python3.9/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python3.9/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
  File "/usr/lib64/python3.9/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python3.9/xmlrpc/client.py", line 1196, in single_request
    raise ProtocolError(
xmlrpc.client.ProtocolError: <ProtocolError for 127.0.0.1:80/cobbler_api: 503 Service Unavailable>
Thu Dec 29 22:07:52 2022 - ERROR - Failed option: mgmtclass add
Thu Dec 29 22:07:54 2022 - ERROR - oe_test_cobbler_mgmtclass.sh line 33
exception on server: 'internal error, unknown mgmtclass name OpenEuler1'
Thu Dec 29 22:08:17 2022 - ERROR - Failed option: mgmtclass copy
Thu Dec 29 22:08:19 2022 - ERROR - oe_test_cobbler_mgmtclass.sh line 37
exception on server: 'internal error, unknown mgmtclass name openEuler1'
Thu Dec 29 22:08:43 2022 - ERROR - Failed option: mgmtclass edit
Thu Dec 29 22:08:45 2022 - ERROR - oe_test_cobbler_mgmtclass.sh line 41
Thu Dec 29 22:08:58 2022 - ERROR - Failed option: mgmtclass list
Thu Dec 29 22:09:00 2022 - ERROR - oe_test_cobbler_mgmtclass.sh line 43
Thu Dec 29 22:09:15 2022 - ERROR - Failed option: mgmtclass find
Thu Dec 29 22:09:16 2022 - ERROR - oe_test_cobbler_mgmtclass.sh line 45
exception on server: 'internal error, unknown mgmtclass name OpenEuler1'
exception on server: 'internal error, unknown mgmtclass name OpenEuler2'
Thu Dec 29 22:10:06 2022 - ERROR - Failed option: mgmtclass rename
Thu Dec 29 22:10:08 2022 - ERROR - oe_test_cobbler_mgmtclass.sh line 53
Thu Dec 29 22:10:25 2022 - ERROR - Failed option: mgmtclass report
Thu Dec 29 22:10:27 2022 - ERROR - oe_test_cobbler_mgmtclass.sh line 55
Thu Dec 29 22:10:28 2022 - INFO  - End to run testcase.
Thu Dec 29 22:10:30 2022 - ERROR - failed to execute the case.
Thu Dec 29 22:10:32 2022 - INFO  - Start to restore the test environment.
Thu Dec 29 22:12:11 2022 - INFO  - End to restore the test environment.
