+ source /root/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n '' ']'
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Mon Dec  5 11:40:38 2022 - INFO  - Start to run test.
+ expect
spawn sqlite3 ./test.db
couldn't execute "sqlite3": no such file or directory
    while executing
"spawn sqlite3 ./test.db"
++ wc -l ./output.txt
++ grep -cE 6
wc: ./output.txt: No such file or directory
+ CHECK_RESULT 0 1
+ actual_result=0
+ expect_result=1
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 1x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_sqlite_select_05.sh line 46'
+ message='oe_test_sqlite_select_05.sh line 46'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_sqlite_select_05.sh line 46'
Mon Dec  5 11:40:39 2022 - ERROR - oe_test_sqlite_select_05.sh line 46
+ return 0
++ wc -l ./output1.txt
++ grep -cE 3
wc: ./output1.txt: No such file or directory
+ CHECK_RESULT 0 1
+ actual_result=0
+ expect_result=1
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 1x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_sqlite_select_05.sh line 47'
+ message='oe_test_sqlite_select_05.sh line 47'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_sqlite_select_05.sh line 47'
Mon Dec  5 11:40:40 2022 - ERROR - oe_test_sqlite_select_05.sh line 47
+ return 0
++ awk NR==1 ./output1.txt
++ grep -cE 3
awk: fatal: cannot open file `./output1.txt' for reading: No such file or directory
+ CHECK_RESULT 0 1
+ actual_result=0
+ expect_result=1
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 1x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_sqlite_select_05.sh line 48'
+ message='oe_test_sqlite_select_05.sh line 48'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_sqlite_select_05.sh line 48'
Mon Dec  5 11:40:41 2022 - ERROR - oe_test_sqlite_select_05.sh line 48
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Mon Dec  5 11:40:42 2022 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 3
+ test 3 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Mon Dec  5 11:40:43 2022 - ERROR - failed to execute the case.
+ exit 3
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Mon Dec  5 11:40:43 2022 - INFO  - Start to restore the test environment.
+ rm -rf ./test.db './output*.txt'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Mon Dec  5 11:40:44 2022 - INFO  - End to restore the test environment.
