+ source /root/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n '' ']'
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Mon Dec  5 11:37:44 2022 - INFO  - Start to run test.
+ expect
spawn sqlite3 ./test.db
couldn't execute "sqlite3": no such file or directory
    while executing
"spawn sqlite3 ./test.db"
+ sqlite3 ./test.db .dump
oe_test_sqlite_command_06.sh: line 36: sqlite3: command not found
+ CHECK_RESULT 127
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_sqlite_command_06.sh line 37'
+ message='oe_test_sqlite_command_06.sh line 37'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_sqlite_command_06.sh line 37'
Mon Dec  5 11:37:45 2022 - ERROR - oe_test_sqlite_command_06.sh line 37
+ return 0
+ rm -rf ./test.db
+ SLEEP_WAIT 2
+ wait_time=2
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 2 --cmd '' --mode 1
+ sqlite3 ./test.db
oe_test_sqlite_command_06.sh: line 40: sqlite3: command not found
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ expect
spawn sqlite3 ./test.db
couldn't execute "sqlite3": no such file or directory
    while executing
"spawn sqlite3 ./test.db"
++ wc -l ./output.txt
++ grep -cE 24
wc: ./output.txt: No such file or directory
+ CHECK_RESULT 0 1
+ actual_result=0
+ expect_result=1
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 1x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_sqlite_command_06.sh line 51'
+ message='oe_test_sqlite_command_06.sh line 51'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_sqlite_command_06.sh line 51'
Mon Dec  5 11:37:55 2022 - ERROR - oe_test_sqlite_command_06.sh line 51
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Mon Dec  5 11:37:56 2022 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 2
+ test 2 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Mon Dec  5 11:37:57 2022 - ERROR - failed to execute the case.
+ exit 2
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Mon Dec  5 11:37:58 2022 - INFO  - Start to restore the test environment.
+ rm -rf ./test.db ./output.txt ./test.sql
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Mon Dec  5 11:37:59 2022 - INFO  - End to restore the test environment.
