+ source /root/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n '' ']'
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Sat Dec  3 13:23:39 2022 - INFO  - Start to run test.
+ openssl genrsa -out rsakey.pem
oe_test_openssl_RSA_algorithm.sh: line 23: openssl: command not found
+ CHECK_RESULT 127
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openssl_RSA_algorithm.sh line 24'
+ message='oe_test_openssl_RSA_algorithm.sh line 24'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openssl_RSA_algorithm.sh line 24'
Sat Dec  3 13:23:40 2022 - ERROR - oe_test_openssl_RSA_algorithm.sh line 24
+ return 0
+ grep 'BEGIN RSA PRIVATE KEY' rsakey.pem
grep: rsakey.pem: No such file or directory
+ CHECK_RESULT 2
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openssl_RSA_algorithm.sh line 26'
+ message='oe_test_openssl_RSA_algorithm.sh line 26'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openssl_RSA_algorithm.sh line 26'
Sat Dec  3 13:23:41 2022 - ERROR - oe_test_openssl_RSA_algorithm.sh line 26
+ return 0
+ openssl rsa -in rsakey.pem -pubout -out rsakey-pub.pem
oe_test_openssl_RSA_algorithm.sh: line 27: openssl: command not found
+ CHECK_RESULT 127
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openssl_RSA_algorithm.sh line 28'
+ message='oe_test_openssl_RSA_algorithm.sh line 28'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openssl_RSA_algorithm.sh line 28'
Sat Dec  3 13:23:42 2022 - ERROR - oe_test_openssl_RSA_algorithm.sh line 28
+ return 0
+ grep 'BEGIN PUBLIC KEY' rsakey-pub.pem
grep: rsakey-pub.pem: No such file or directory
+ CHECK_RESULT 2
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openssl_RSA_algorithm.sh line 30'
+ message='oe_test_openssl_RSA_algorithm.sh line 30'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openssl_RSA_algorithm.sh line 30'
Sat Dec  3 13:23:43 2022 - ERROR - oe_test_openssl_RSA_algorithm.sh line 30
+ return 0
+ generate_PublicKey
oe_test_openssl_RSA_algorithm.sh: line 31: generate_PublicKey: command not found
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Sat Dec  3 13:23:43 2022 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 4
+ test 4 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Sat Dec  3 13:23:44 2022 - ERROR - failed to execute the case.
+ exit 4
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Sat Dec  3 13:23:45 2022 - INFO  - Start to restore the test environment.
+ rm -f rsakey.pem rsakey-pub.pem mycert-rsa.pem testlog
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Sat Dec  3 13:23:46 2022 - INFO  - End to restore the test environment.
